---
title: Dependencias y Propiedades de objetos del INE.
---
flowchart TD
    O[Operación]
    Var[Variable]
    Val[Valor]
    ValH[Valores Hijos]
    Tab[Tabla]
    GT[Grupo Tablas]
    S[Serie]
    D[Datos]
    P[Publicación]
    FP[Fecha Publicación]
    U[Unidad]
    E[Escala]
    Pr[Periodo]
    Pi[Periodicidad]
    Cl[Clasificación]
    %% Relaciones
    %% Dependencias

    O -.-> Var
    subgraph variable_valor
    Var -.-> Val
    end
    O -.-> Tab --> GT

    O OS@-.-> S
    Tab TS@-.-> S
    OS@{animate: true}
    TS@{animate: true}

    O -.-> P -.-> FP

    O -.-> Cl

    %% Propiedades
    Tab ==> Pi
    Tab ==> P
    Tab ==> Pr

    Val --> ValH

    S ==> Pi
    S ==> P
    S ==> Cl
    S ==> U
    S ==> E
    S ==> D

    Pr ==> Pi

    P ==> Pi
    %% Filtros
    variable_valor -.-> S
    linkStyle 21 stroke:#ff3,stroke-width:4px;

    Cl -.-> Val
    linkStyle 22 stroke:#ff3,stroke-width:4px;

    %% Diagram Notes
    V1[ ]
    V2[ ]
    V3[ ]
    V4[ ]
    V5[ ]
    V6[ ]

    V1 -.->|Dependencia| V2 ==>|Propiedad| V3 -->|Ambos| V4 V@-->|Alternativa| V5 -.->|Filtra| V6
    V@{animate: true}
    linkStyle 27 stroke:#ff3,stroke-width:4px;